### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/TrainSet.mat'

### ISSUE THREAD

**Issue by np000** [nachiket92/conv-social-pooling#3]
Hello,
could you also please upload the dependent files,
Thanks in advance!

Error log

/home/npv0/exp/pytorch/venvpytorch/bin/python /home/npv0/exp/conv-social-pooling/train.py
Traceback (most recent call last):
  File "/home/npv0/exp/pytorch/venvpytorch/lib/python3.5/site-packages/scipy/io/matlab/mio.py", line 33, in _open_file
    return open(file_like, 'rb'), True
FileNotFoundError: [Errno 2] No such file or directory: 'data/TrainSet.mat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/npv0/exp/conv-social-pooling/train.py", line 44, in <module>
    trSet = ngsimDataset('data/TrainSet.mat')
  File "/home/npv0/exp/conv-social-pooling/utils.py", line 14, in __init__
    self.D = scp.loadmat(mat_file)['traj']
  File "/home/npv0/exp/pytorch/venvpytorch/lib/python3.5/site-packages/scipy/io/matlab/mio.py", line 141, in loadmat
    MR, file_opened = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/home/npv0/exp/pytorch/venvpytorch/lib/python3.5/site-packages/scipy/io/matlab/mio.py", line 64, in mat_reader_factory
    byte_stream, file_opened = _open_file(file_name, appendmat)
  File "/home/npv0/exp/pytorch/venvpytorch/lib/python3.5/site-packages/scipy/io/matlab/mio.py", line 39, in _open_file
    return open(file_like, 'rb'), True
FileNotFoundError: [Errno 2] No such file or directory: 'data/TrainSet.mat'

**Comment by DanqingZ** [comment]
+1 could you provide the dependent data files? Thank you. Would like to try out your network.

**Comment by Binbose** [comment]
The old link https://www.its-rde.net/index.php/rdedataenvironment/10023 to download the data is deprecated, the new location https://data.transportation.gov/Automobiles/Next-Generation-Simulation-NGSIM-Vehicle-Trajector/8ect-6jqj puts all data in one big file though. I tried to split the data according to the time stemps, but when running 'preprocess_data.m', I get an error in line 193, telling me that I exceed the matrix dimensions. 
Could you maybe upload the processed data on a file sharing platform?

**Comment by nextfeixiag** [comment]
> The old link https://www.its-rde.net/index.php/rdedataenvironment/10023 to download the data is deprecated, the new location https://data.transportation.gov/Automobiles/Next-Generation-Simulation-NGSIM-Vehicle-Trajector/8ect-6jqj puts all data in one big file though. I tried to split the data according to the time stemps, but when running 'preprocess_data.m', I get an error in line 193, telling me that I exceed the matrix dimensions.
> Could you maybe upload the processed data on a file sharing platform?

can't open the link...

**Comment by nextfeixiag** [comment]
> The data files are too large to upload to Github. The 'preprocess_data.m' file generates these files from the raw NGSIM US-101 and I-80 text files. These are publicly available datasets.

Hai....in the  'preprocess_data.m' file what does the  ' Lateral maneuver' and 'Longitudinal maneuver' means?

**Comment by nachiket92** [comment]
These are the maneuver classes as described in the paper

**Comment by ailib** [comment]
> The data files are too large to upload to Github. The 'preprocess_data.m' file generates these files from the raw NGSIM US-101 and I-80 text files. These are publicly available datasets.

can provide  the raw NGSIM US-101 and I-80 text file, or the links, thanks

**Comment by huling121** [comment]
> These are the maneuver classes as described in the paper

hello,Now all the downloaded data is in a big folder. Does this folder contain us-101 and i-80?Then "preprocess data" generates the corresponding 6 files? thank you very much!

**Comment by huling121** [comment]
> These are the maneuver classes as described in the paper

"Next_generation_simulationingingle_trajectories_and_supporting_data" in 'location' I only see peachtree and us-101 but not i-80, I wonder if there is something wrong with the data I downloaded?Or, it looks like this
